--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ihsan48/BossAnnouncement
projects:
  BossAnnouncement:
    path: ""
    libs:
    - src: thebigsmilexd/apibossbar/apibossbar
      version: ^0.1.5
      branchs: PM4
...